name: Build
on:
  workflow_call:
    inputs:
      workload_identity_provider:
        type: string
      service_account:
        type: string
      gar_repository:
        type: string
      gar_dst:
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GAR
        run: gcloud auth configure-docker ${{ inputs.gar_repository }} --quiet
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.amd64
          platforms: linux/amd64
          push: true
          tags: |
            ${{ inputs.gar_dst }}:latest
