name: CI

on:
  push:
    branches:
      - add-ci
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Dependencies
        run: npm ci

      - name: Test and Build
        run: npm install -g pkg && npm test && npm run build
  build:
    uses: ./.github/workflows/_build.yml
    needs: ci
    if: ${{ !failure() && github.ref_name == 'add-ci' }}
    with:
      workload_identity_provider: projects/723082692741/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-provider
      service_account: reearth-dev-github-oidc@reearth-development.iam.gserviceaccount.com
      gcs_dst: gs://app.dev.reearth.io
