name: Deploy reearth help prod
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      environment: production
      gar_repository: asia-northeast1-docker.pkg.dev
    secrets: inherit
  deploy:
    runs-on: ubuntu-latest
    environment: development
    needs: build
    if: ${{ !failure() }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy reearth-help \
            --image $IMAGE_NAME \
            --region $GCP_REGION \
            --platform managed \
            --quiet
        env:
          GCP_REGION: asia-northeast1
          IMAGE_NAME: ${{ secrets.IMAGE_NAME_GAR }}:latest
