name: Deploy prod
on:
  workflow_dispatch:
env:
  IMAGE_NAME_GAR: asia-northeast1-docker.pkg.dev/reearth/eukarya/notion-proxy
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/950334725361/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-provider
  GCP_SERVICE_ACCOUNT: reearth-prod-github-oidc@reearth.iam.gserviceaccount.com
  GCP_REGION: asia-northeast1
jobs:
  # TODO: Refactor with and env param
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      workload_identity_provider: projects/950334725361/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-provider
      service_account: reearth-prod-github-oidc@reearth.iam.gserviceaccount.com
      gar_repository: asia-northeast1-docker.pkg.dev
      gar_dst: asia-northeast1-docker.pkg.dev/reearth/eukarya/notion-proxy
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !failure() }}
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy reearth-help \
            --image $IMAGE_NAME \
            --region $GCP_REGION \
            --platform managed \
            --quiet
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME_GAR }}:latest
